# Site settings
title:          雑記
description:    "がんばります"
baseurl:        "/blog"
url:            "http://kobaryo222.com"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Ryohei Kobayashi
  url:          https://twitter.com/6Lgug
  email:        kobaryo222912@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title:output_ext
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec, Makefile]

# KaTeX
kramdown:
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale